extends: default
ignore: |
  charts/*/templates/
  charts/*/charts/
rules:
  line-length:
    max: 200
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
